services:
  verdaccio: 
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - VERDACCIO_PORT=4873
      - VERDACCIO_PROTOCOL=http
    ports: 
      - "4873:4873"
    volumes: 
      - "./packages:/verdaccio/storage/data"
